### PR TITLE
Set

### PR DESCRIPTION
**Pull request by HaritzPuerto**
@zeronone There some tests that fails because I don't know how to write them. Could you help me out? 고마워~

### CODE REVIEW

**Comment by HaritzPuerto** [comment]
I have to upload a new version of the implementation. But right now I can't. The proxy of my home university doesn't allow me to use github... :cry:

**Comment by zeronone** [comment]
I checked the implementation. I think most of the problems rise from the covariant type-parameters. I will try to add another implementation of Sets using abstract type members tonight.

**Comment by zeronone** [comment]
I added my implementation of Sets. Check #16

**Comment by HaritzPuerto** [comment]
@zeronone I think my implementatio is ok as I don't have compile errors, I made a few tests with a driver which works well and it's based on the implementation of my prof. in Haskell. My problems are only on the tests because I don't know how to write them.

**Comment by zeronone** [comment]
@HaritzPuerto I updated the tests, check if it works now.

**Comment by HaritzPuerto** [comment]
I have just discovered a problem...
EmptySet.delete(0).isEmpty() = false why?!!! I don't understand that

**Comment by zeronone** [comment]
@HaritzPuerto: I refined the code structure and now all the tests passes. 
The test properties were wrong. In the problematic tests, you were actually intending the implication operator (==>) but using the AND operator (&&). I fixed the tests and put some comments, please take a look. 

Although I saw many places that the file name didn't matched withe enclosing class or object. It is a good practice to use consistent names.

**Pull request merged**
