### PR TITLE
Sbt integration

### PR DESCRIPTION
**Pull request by zeronone**
This one should work. I updated it and included your queue implementation. 
I also modified a little the queue property testing. 

Now `sbt test` works.

### CODE REVIEW

**Comment by zeronone** [comment]
It works very good in Intellij. But the `sbt eclipse` works okay, but the directory structure is messed up when importing the project.

**Comment by HaritzPuerto** [comment]
ok. I'll check it tomorrow. thnx!

**Comment by HaritzPuerto** [comment]
http://ctrlv.in/592848
@zeronone 
I've obtained this. Is this ok? I think so. If so, fell free to merge :smile:

**Comment by zeronone** [comment]
@HaritzPuerto Yeah it seems fine. The directory structure is flat. But I couldn't get it to the tree view. However if you open it in IntelliJ everything is good. 

It is good to merge :smile:

**Pull request merged**
