### PR TITLE
Bst haritz

### PR DESCRIPTION
**Pull request by HaritzPuerto**
@FelipeSulser check if this works. Note that I have each case class in a different file and I've used and object oriented approach

### CODE REVIEW

**Comment by FelipeSulser** [comment]
Still has the following errors:
In abstract class BSTree[+T] : 
covariant type T occurs in contravariant position in type Tree.BSTree[T] of value t

What does this mean?

**Comment by HaritzPuerto** [comment]
ohhh Some[_] and None seems very elegant and useful. Thanks @zeronone I didn't know them
http://alvinalexander.com/scala/using-scala-option-some-none-idiom-function-java-null

**Comment by HaritzPuerto** [comment]
All tests are GREEN! Good job @zeronone 잘 했어~

**Comment by HaritzPuerto** [comment]
@FelipeSulser in Scala you don't need to used java equals. == is function not a pointer equal operator. You may have already seen it when I defined comparators for some data structures. Am I right? @zeronone

**Comment by zeronone** [comment]
Yes that is right. == is just the same as any other function. Scala's syntax allows you to write x == y instead of x.==(y)

**Comment by HaritzPuerto** [comment]
@zeronone  I have a problem with the apply funciton. I have created a companion object to enforce the constructor to fulfill the constraints of any BST, but it doesn't compile because I have 2 definitions of apply function. Do you know what I am doing wrong? thnx

**Comment by HaritzPuerto** [comment]
@FelipeSulser I've finished! All tests are green :)

**Pull request merged**
